# Generated by Django 5.0.6 on 2024-06-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendee_attendee_unique_attendee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='core.attendee')),
            ],
            options={
                'db_table': 'check_ins',
            },
        ),
    ]
