apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nlw-passin
  namespace: argocd

spec:
  project: default
  source:
    repoURL: git@github.com:igorgcardoso/pass-in-NLW.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nlw
  syncPolicy:
    automated:
      prune: true
